//! 按锚点清单与期望登记在编译期展开矩阵单元为具名测试，例如 `d1::a13_to_head`。

use std::{env, fs, path::PathBuf};

use serde_json::Value;

fn main() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap_or_default());
    let expectations_path = manifest.join("expectations.json");
    println!("cargo::rerun-if-changed={}", expectations_path.display());
    println!(
        "cargo::rerun-if-changed={}",
        manifest.join("anchors.json").display()
    );
    let expectations: Value = match fs::read_to_string(&expectations_path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
    {
        Some(value) => value,
        None => panic!("tests/upgrade-matrix/expectations.json must be valid JSON"),
    };
    let mut modules: Vec<(String, Vec<String>)> = Vec::new();
    for cell in expectations["cells"].as_array().into_iter().flatten() {
        let Some(id) = cell["cell"].as_str() else {
            panic!("expectation entry without cell id");
        };
        let (dimension, rest) = id.split_once('-').unwrap_or((id, ""));
        let name = test_name(rest);
        let test = format!(
            "    #[tokio::test(flavor = \"multi_thread\", worker_threads = 4)]\n    async fn {name}() {{\n        uc_upgrade_matrix::run_cell(\"{id}\").await;\n    }}\n"
        );
        match modules.iter_mut().find(|(module, _)| module == dimension) {
            Some((_, tests)) => tests.push(test),
            None => modules.push((dimension.to_owned(), vec![test])),
        }
    }
    let mut source = String::from("// @generated by tests/upgrade-matrix/build.rs\n");
    for (module, tests) in modules {
        source.push_str(&format!("mod {module} {{\n"));
        for test in tests {
            source.push_str(&test);
        }
        source.push_str("}\n");
    }
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap_or_default()).join("cells.rs");
    if fs::write(&out, source).is_err() {
        panic!("cannot write generated matrix cells");
    }
}

/// `a13-head` -> `a13_to_head`；`a13-head-old-inviter` -> `a13_to_head_old_inviter`；`chain` 不变。
fn test_name(rest: &str) -> String {
    let parts: Vec<&str> = rest.split('-').collect();
    if parts.len() >= 2 {
        let mut name = format!("{}_to_{}", parts[0], parts[1]);
        for part in &parts[2..] {
            name.push('_');
            name.push_str(part);
        }
        name
    } else {
        rest.replace('-', "_")
    }
}
